apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nqsyhstk
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-nqsyhstk:f859abb69a5610a6eae2118954879bfd726715e6@sha256:0a084f12a8f38f5c0cd268715b6d5316bb762ee25ecb0581c76ead2e9f4e22e7
          name: container-image
